name: Test, Build, and Deploy

on:
  push:
    branches:
      - develop
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > backend/.env

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: "npm"
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install and test frontend
        run: npm run test:frontend

      - name: Install and test backend
        run: npm run test:backend

      - name: Build
        run: npm run build

      - name: Setup for deploy
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
