name: Merge Test and Deploy

on:
  push:
    branches: ["main"]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test and build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install and test frontend
        run: cd frontend && npm ci
        run: npm test

      - name: Install and test backend
        run: cd ../backend && npm ci
        run: npm test

      - name: Build
        run: npm run build:ui

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    needs: test and build
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:   
          name: node-app

      - name: Deploy to Fly.io
        uses: actions/checkout@v3
        uses: superfly/flyctl-actions/setup-flyctl@master
        run: flyctl deploy --remote-only
